spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5433/etaskify
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  liquibase:
    default-schema: etaskify
    enabled: false

